### ISSUE TITLE
Implement Change Password Page

### ISSUE THREAD

**Issue by saidghamra** [AgoraCloud/ui#10]
We need to:
- [x] Implement basic form functionality to change a users password
- [x] Show validation errors
- [x] Show a pop up or something with error message on POST 3xx, 4xx and 5xx status codes
- [x] Disable change password button with invalid input
- [x] On failure or success, clear the input forms after the submit button is pressed

**Comment by MarcDAFrame** [comment]
Change password page has been implemented and styled
