### ISSUE TITLE
Implement Verify Account Page

### ISSUE THREAD

**Issue by saidghamra** [AgoraCloud/ui#11]
We need to:
- [x] Implement basic form functionality to verify an account
- [x] Style the page
- [x] Display error messages in the dialog

**Comment by saidghamra** [comment]
When there is an error:
- [ ] Text is displayed in red with an error icon
- [ ] Display a `Go Back to Sign In` button under the error message

**Comment by MarcDAFrame** [comment]
implemented the additional styling and the new button, tested and everything works great !
