### ISSUE TITLE
Implement Projects Page

### ISSUE THREAD

**Issue by saidghamra** [AgoraCloud/ui#15]
As a user, I should be able to CRUD projects. The interface would look similar to GitHub's projects:

![image](https://user-images.githubusercontent.com/35788699/110959528-c8bb3600-831b-11eb-9796-ca9da1e1d758.png)

**Comment by MarcDAFrame** [comment]
![image](https://user-images.githubusercontent.com/12240832/110965285-091db280-8322-11eb-8555-4830c7a9498f.png)

**Comment by MarcDAFrame** [comment]
## Possible Resources

https://codesandbox.io/embed/simple-kanban-board-latest-r9bpe?fontsize=14

https://medium.com/@RethnaGanesh/developing-a-kanban-board-using-react-dnd-and-react-hooks-1cae2e11ea99

## NPM package with it already done
https://www.npmjs.com/package/react-dnd-kanban

**Comment by saidghamra** [comment]
- [ ] Clear the create project form on `Cancel` or `Create`

**Comment by saidghamra** [comment]
In `develop`
