### ISSUE TITLE
Implement Workspace Settings Page

### ISSUE THREAD

**Issue by saidghamra** [AgoraCloud/ui#18]
As a workspace administrator, I should be able to:
- [x] Update the workspace name
- [x] Update the workspace resource quotas (cpu, memory and storage)
- [x] Delete the workspace

To accomplish this, we will have a workspace section in the side menu with three buttons:
- [x] `Create Workspace`
- [x] `Settings`
- [x] `Metrics`

**Comment by waleedza99** [comment]
Unable to write any code or create new files as I inherited errors from @MarcDAFrame. The errors pushed into the develop branch need to be fixed by @MarcDAFrame so the develop branch can become error-free and I can finally start working again...

**Comment by saidghamra** [comment]
In `develop`
