### ISSUE TITLE
Workspace and Deployment Ids Should Be Reflected in the URL

### ISSUE THREAD

**Issue by saidghamra** [AgoraCloud/ui#20]
The URL should follow the following format when signed in and in the main dashboard:

- [x] When a workspace is selected: https://domain.com/app/w/:workspaceId
- [x] When a workspace is selected and in the deployments page: https://domain.com/app/w/:workspaceId/d
- [x] When a workspace and deployment are selected: https://domain.com/app/w/:workspaceId/d/:deploymentId

**Comment by MarcDAFrame** [comment]
Had to develop a screen for when there are no workspaces on the route `/w/new`

this implements Waleed's New Workspace Dialog

**Comment by saidghamra** [comment]
Will be merged to `develop`
