### ISSUE TITLE
Indicate Needed Node Version in README

### ISSUE THREAD

**Issue by parvizi** [AgoraCloud/ui#26]
Please update the readme. The git repo should be cloned, and probably you need to determine prerequisite such as nodejs and npm version. I also received this error.

npm ERR! Linux 4.4.0-18362-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! agoracloud_ui@0.0.1 start: `webpack-dev-server --mode development --hot --progress --colors --port 3000 --open`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the agoracloud_ui@0.0.1 start script 'webpack-dev-server --mode development --hot --progress --colors --port 3000 --open'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the agoracloud_ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --mode development --hot --progress --colors --port 3000 --open
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs agoracloud_ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls agoracloud_ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/alireza/ui/npm-debug.log

**Comment by saidghamra** [comment]
Hi @parvizi,

It looks like you are using Node version 8.10.0, [which has been deprecated](https://blog.risingstack.com/update-nodejs-8-end-of-life-no-support/). For the ui, you need at-least version 10. We will update the README with the required Node version today. Thank you for letting us know!

**Comment by saidghamra** [comment]
In `develop`
