### ISSUE TITLE
Implement Create Workspace Functionality

### ISSUE THREAD

**Issue by saidghamra** [AgoraCloud/ui#28]
The user needs to be able to create a workspace. We can create a `Create Workspace` button in the workspace dropdown or at the bottom of the side menu.

[Dialog Documentation](https://material-ui.com/components/dialogs/)

**Comment by MarcDAFrame** [comment]
https://material-ui.com/components/floating-action-button/

![image](https://user-images.githubusercontent.com/12240832/107818647-ef4e7700-6d45-11eb-9e6d-f0615a460856.png)
* floating action button in the bottom right

**Comment by saidghamra** [comment]
In `develop`
