### ISSUE TITLE
Finish Deployments Functionality

### ISSUE THREAD

**Issue by saidghamra** [AgoraCloud/ui#33]
## Description

- [x] Update a deployment
- [x] Deployment proxy
- [x] Delete a deployment
- [x] Create a info page where users can:
    - [x] See deployment logs
    - [x] See deployment metrics (resource usage)
- [x] Add rocket icon to `LAUNCH` button
- [x] Disable `LAUNCH` button if deployment is not running
- [x] Fix the deployment card scaling (max width 333px)

**Create Deployment Quick Fixes:**

- [x] CPU and RAM input fields should be mandatory
- [x] Add a switch `Persist`, if enabled show the mandatory storage input field
- [x] Load all available deployment images via the `api/workspaces/:workspaceId/images` endpoint
- [x] Rename Sudo Password field to Sudo Password
- [x] Reset create deployments form on creation or navigation away from the create deployments page

**Comment by MarcDAFrame** [comment]
**Quick Fixes:**

- [ ] CPU and RAM input fields should be mandatory
- [ ] Add a switch `Persist`, if enabled show the mandatory storage input field
- [ ] Load all available deployment images via the `api/workspaces/:workspaceId/images` endpoint
- [x] Rename Sudo Password field to Sudo Password
- [ ] Reset create deployments form on creation or navigation away from the create deployments page

**Comment by MarcDAFrame** [comment]
![image](https://user-images.githubusercontent.com/12240832/109700039-4aaea080-7b5f-11eb-93d4-47ed7da5aecb.png)
source: coder.com

example of what the metrics page will look like for workspaces and deployments

**Comment by MarcDAFrame** [comment]
![image](https://user-images.githubusercontent.com/12240832/109700113-64e87e80-7b5f-11eb-98ac-8f8cae1c745f.png)
source: console.firebase.google.com 

example of what the log tables will look like for audit, deploments, and workspaces

**Comment by MarcDAFrame** [comment]
`edit deployment` page will look just like the `create deployment` page but with prepopulated input fields
![image](https://user-images.githubusercontent.com/12240832/109700965-741bfc00-7b60-11eb-940d-0e3730ea75c3.png)

**Comment by MarcDAFrame** [comment]
https://plotly.com/javascript/gauge-charts/

for the metrics page

**Comment by MarcDAFrame** [comment]
![image](https://user-images.githubusercontent.com/12240832/111212189-ad635b80-85a5-11eb-9bbf-5a44ef5a3475.png)

final log page
just need to 
- [ ] scale the gauge by width (plotly is acting funny)

**Comment by saidghamra** [comment]
In `develop`
