### ISSUE TITLE
Implement User Management

### ISSUE THREAD

**Issue by MarcDAFrame** [AgoraCloud/ui#39]
## Workspace Admins
- [x] List all users within workspace
- [x] Create a user
- [x] Delete users
- [x] Change password
- [x] Enable / disable users
- [x] Verify / un-verify users
- [x] Invite users to workspace
## Super Admins
- all of the above but across all workspaces and users

## Example of a user table
![image](https://user-images.githubusercontent.com/12240832/110959696-f86a3e00-831b-11eb-8259-cb6b33c26edb.png)

**Comment by MarcDAFrame** [comment]
![image](https://user-images.githubusercontent.com/12240832/112199727-d5297380-8be4-11eb-9622-3b0079db8ade.png)

todo: 
- [ ] add function to the menu buttons (currently they just console.log)
- [ ] get this to work for Workspace Admins

**Comment by saidghamra** [comment]
- [ ] Mask the password when an admin edits a user

**Comment by saidghamra** [comment]
In `develop`
