### ISSUE TITLE
Workspace Select Should Only Be Visible on /w/:wid Domains

### ISSUE THREAD

**Issue by MarcDAFrame** [AgoraCloud/ui#47]
Currently when on other domains besides `/w/:wid` (such as `/admin`) users can see the Workspace Select.

This causes some errors in the console because the Select is 'uncontrolled'

**Comment by MarcDAFrame** [comment]
![image](https://user-images.githubusercontent.com/12240832/112205275-0311b680-8beb-11eb-8da2-29591d3add1e.png)

**Comment by saidghamra** [comment]
We tried to replicate this today but we could not. Regardless, we will keep our eyes on the console logs. If the issue is not observed in a few weeks, we will close this.

**Comment by saidghamra** [comment]
Already fixed via @MarcDAFrame's package integration in #66
