### ISSUE TITLE
Code Refactoring - Part 2 - Change File Structure and Rename Files

### ISSUE THREAD

**Issue by saidghamra** [AgoraCloud/ui#60]
This issue is part 2 of the multi part process of refactoring the code base.

In this issue, Waleed will go through the code base and:
- [x] Rename files based upon agreed naming convention (lowercase for files and folders)
- [x] Restructure files based upon agreed file structure
- [x] Small fixes and improvements (see [this comment](https://github.com/AgoraCloud/ui/issues/59#issuecomment-847283581))
- [x] Remove `console.log()`'s

**Comment by MarcDAFrame** [comment]
/app
  /Workspace
    /Deployments
      index.tsx // component
    /models
      index.ts
    /forms
      index.ts
    /Wiki
      index.tsx
      /models
        index.ts
      /forms
        index.ts
     /Projects
        index.tsx
        /models
          index.ts
        /forms
          index.ts
        /Lanes
           index.tsx
           /models
             index.ts
           /forms
             index.ts
           /Tasks
             index.tsx
             /models
               index.ts
             /forms
               index.ts
  /Stores
  /Config
  /Constants
  /containers

**Comment by saidghamra** [comment]
In `develop`
