### ISSUE TITLE
Code Refactoring - Part 2 - Create Package for Forms, Models and API Calls

### ISSUE THREAD

**Issue by saidghamra** [AgoraCloud/ui#61]
This issue is part 2 of the multi part process of refactoring the code base.

In this issue, Marc will work on an npm package that will be used to abstract:
- Forms
- Data models
- API calls

**Comment by saidghamra** [comment]
Marc is currently working on the base package that will be used to construct a package specific to AgoraCloud's UI.
- [Repository](https://github.com/mars-manjs/models#readme)
- [NPM Package](https://www.npmjs.com/package/@mars-man/models)

**Comment by MarcDAFrame** [comment]
https://www.npmjs.com/package/@mars-man/models
https://github.com/mars-manjs/models

got it published as an npm package as I'm going to be using this in my other projects and at work.

going to begin implementing it in agoracloud once it is rounded out

**Comment by saidghamra** [comment]
Marc has used the `[mars-man/models](https://www.npmjs.com/package/@mars-man/models)` package and integrated it for a work project. He has identified two issues that he needs to resolve before he uses this package to build it as a solution for AgoraCloud.

**Comment by MarcDAFrame** [comment]
https://github.com/mars-manjs/models/issues/2
https://github.com/mars-manjs/models/issues/1

tracking these issues here

**Comment by saidghamra** [comment]
@MarcDAFrame will be working on the [@mars-man/models package](https://www.npmjs.com/package/@mars-man/models) and finalizing the changes needed for events and Typescript types this weekend.

**Comment by saidghamra** [comment]
Done 🎊
