### ISSUE TITLE
Research End to End Testing Strategy before Implementation

### ISSUE THREAD

**Issue by saidghamra** [AgoraCloud/ui#74]
We need to figure out what testing strategy we are going to use for testing the UI. It currently looks like we are going to implement unit tests. We will update the issue when we do decide on what testing strategy we are going to use.

**Comment by MarcDAFrame** [comment]
https://www.youtube.com/watch?v=7N63cMKosIE

https://testing-library.com/docs/cypress-testing-library/intro/

**Comment by waleedza99** [comment]
After reviewing a few well-known e2e testing frameworks like puppeteer, selenium, and cypress, I found cypress to be the most intuitive and easy to use compared to the other frameworks. Cypress is a batteries-included framework that uses Mocha and Chai under the hood. Cypress also has extensive API documentation which is easy to read.

**Comment by saidghamra** [comment]
Based on @waleedza99's feedback and demo today showcasing `cypress` running an authentication end to end test suite, we have decided to move forward with writing end to end tests for our testing strategy, using `cypress`.
