### ISSUE TITLE
Upgrade Module from commonjs to esmodule

### ISSUE THREAD

**Issue by MarcDAFrame** [AgoraCloud/ui#78]
AgoraCloud currently uses `webpack` as the build tool, which compiles the code into CommonJS

We will be moving the build tool to Vite

`@mars-man/models` uses esmodules so we figured it's best to upgrade agoracloud to esmodules instead of downgrading `@mars-man/models`.

The benefits of switiching to ESModules is 
1. smaller bundle sizes due to tree shaking abilities
2. faster build tool ( milliseconds - seconds instead of 40 - 50 seconds )
3. more future proof (ESModules are the future of JS)
4. alignment with the `server` which is ESModules

Downsides include
1. less support (however all of our dependencies support es modules)
2. migration can be a *PAIN in the neck*

**Comment by saidghamra** [comment]
The high priority label has been applied as it blocks #66

**Comment by saidghamra** [comment]
Done 🎊
