### ISSUE TITLE
Remove Store Injection from components

### ISSUE THREAD

**Issue by MarcDAFrame** [AgoraCloud/ui#79]
# Suggestion
we should change the way we inject mobx stores to be cleaner, there is little need to use the old `inject` method

https://github.com/mobxjs/mobx/issues/300#issuecomment-223704275
- this comment outlines the more 'modern' way to inject mobx stores

# what we currently have
```tsx
const Component = inject(STORE_NAME)(observer((props) => {
    const store = props[STORE_NAME] as Store
    ...
}))
...
```
# Option 1: React Context
- using react context / hooks
- this is the recommended way
```tsx
// store-context.ts
import React from 'react'
import rootStore from 'app/stores/RootStore'
export const storesContext = React.createContext(rootStore.stores)

// use-store.ts
import React from 'react'
import { storesContext } from 'app/contexts/store-context'
export const useStores = () => React.useContext(storesContext)

const Component = observer((props) => {
    const {store} = useStores()
    ...
}
```
# Option 2: import the store directly into the component file
- the easiest / cleanest way 
- testing is more difficult
```tsx

// stores.ts
export const store = new Store()
// component.ts
import {store} from 'app/stores'

const Component = observer((props) => {
    ...
}
```

**Comment by MarcDAFrame** [comment]
We will go with option 1 because we are going to be implementing testing (#74)

**Comment by saidghamra** [comment]
@MarcDAFrame will be working on this while integrating the mars-man/models package into the UI

**Comment by saidghamra** [comment]
Fixed by @MarcDAFrame via the package integration in #66
