### ISSUE TITLE
finish Vite implementation: PROXY_TARGET environment variable, cookieDomainRewrite

### ISSUE THREAD

**Issue by MarcDAFrame** [AgoraCloud/ui#80]
this was in webpack, but wasn't added when we switched to vite

# PROXY_TARGET
enables us to run locally with a different environment (dev / prod / marc / waleed...)

# cookieDomainRewrite

without cookie domain rewrite calls are successful with the server, but the cookies are not saved to `localhost:3000`.

As such, it says "Successfully logged in" but the page doesn't update.

```ts
// change this
'/api' : 'https://marc.agoracloud.saidghamra.com',

// to this
'/api': {
    target: 'https://marc.agoracloud.saidghamra.com',
    changeOrigin: true,
    cookieDomainRewrite: ""
},
```

**Comment by saidghamra** [comment]
Done 🎊
