### ISSUE TITLE
Implement Reset Password Page

### ISSUE THREAD

**Issue by saidghamra** [AgoraCloud/ui#9]
We need to:
- [x] Implement basic form functionality to reset password
- [x] Show validation errors
- [x] Show a pop up or something with error message on POST 3xx, 4xx and 5xx status codes
- [x] Disable reset password button with invalid input
- [x] On failure or success, clear the input forms after the submit button is pressed

**Comment by waleedza99** [comment]
This page is nearly (97%) complete, I'm waiting for Marc to implement the reset function which will clear out the forms. Once Marc finishes that I will use his function to clear out the form on this page and finally finish off the last task in the checklist

**Comment by waleedza99** [comment]
the form on the forgot password page now clears up whenever the user submits form data, so this page is fully complete
