### ISSUE TITLE
Integrate the `mars-man/models` Package into Projects, Project Lanes and Project Tasks

### ISSUE THREAD

**Issue by saidghamra** [AgoraCloud/ui#90]
# Overview

In this issue, @MarcDAFrame will finalize the integration of the mars-man/models package for projects, project lanes and project tasks 🎉 

# To Do
- [x] Projects
- [x] Project lanes
- [x] Project tasks

**Comment by MarcDAFrame** [comment]
@saidghamra  found some bugs when testing 

- When I edit a task and update the title or description, I have to refresh to view the changes. I can also see 2 success snackbars that say "Project Task Successfully"?
- When I edit a project lane, the lane name is not populated in the Name input
- Deleting a project lane does not work

**Comment by MarcDAFrame** [comment]
I added a snackbar boolean to the event types which says whether to show a snackbar 

`file: src/app/constants/events.ts`

```
  LANE_TASK_CRUD: {
    onLoad: {
      type: 'LANE_TASKS_CRUD',
      snackbar: false,
      data: {
        message: 'Project Task Successfully: ',
        variant: 'success',
      },
    },
    onError: {
      type: 'LANE_TASKS_ERR',
      snackbar: false,
      data: {
        message: 'Project Task Failure: ',
        variant: 'error',
      },
    },
  },
```

**Comment by saidghamra** [comment]
Projects, project lanes and project tasks are functioning perfectly now 🎉

**Comment by saidghamra** [comment]
Done 🎉
