### ISSUE TITLE
Small bugs caught in our weekly demo

### ISSUE THREAD

**Issue by MarcDAFrame** [AgoraCloud/ui#91]
- [x] wiki page causes react error
- [x] edit project name doesn't update project model
- [x] EditDeployment
    - [x] change edit-> update
    - [x] buttons should go to workspace home
- [x] add ScalingMethod to DeploymentCard
- [x] if there are only favorited deployments / only non-favorited deployments don't show the accordion
- [x] workspace should be able to be created with only a name provided (currently you have to include resources)
- [x] edit deployment should only be able to select higher versions

**Comment by MarcDAFrame** [comment]
```
npm run build; npm run serve
```
using this to test for build errors (ala the minified react error of 'wiki page causes react error')

**Comment by MarcDAFrame** [comment]
found another bug
- [ ] `/w/new` throws error when navigated to before workspaces have loaded. this is due to not using the workspaceloaded route guard

**Comment by saidghamra** [comment]
- [ ] Use the deployment labeling util from `@agoracloud/common` to convert the deployment status to a human readable status
- [ ] When I edit the name of a wiki page, the name isn't updated in the sidebar
- [ ] Scaling method should be right next to the deployment status pill (on the same line)
- [ ] When I edit the name of a deployment, I can not click the `UPDATE` button (seems to happen after you did the deployment version select update)
- [ ] Remove the `*` label from CPU Cores, RAM and Storage input fields in the create workspace form (all these fields are optional)

**Comment by MarcDAFrame** [comment]
finished everything except
> When I edit the permissions of a workspace user or an application wide user, clicking the EDIT button should close the modal

because I thought this was purposeful.

Because the permissions form is a more complex form, closing it on the user might lead to bad UX.

i.e. a user might want to edit but still be able to view what they have just done. The additional click away from the user is worth it for them to not be frustrated by it not closing on them when they don't want it to.

**Comment by saidghamra** [comment]
> finished everything except
> 
> > When I edit the permissions of a workspace user or an application wide user, clicking the EDIT button should close the modal
> 
> because I thought this was purposeful.
> 
> Because the permissions form is a more complex form, closing it on the user might lead to bad UX.
> 
> i.e. a user might want to edit but still be able to view what they have just done. The additional click away from the user is worth it for them to not be frustrated by it not closing on them when they don't want it to.

Every other modal in the UI that allows the user to edit data closes when the user clicks the edit or update action button. If we are demoimg this and every single form closes when we hit edit or update besides this one, the first thought that comes to mind from the attendees would be "this is a bug"...

**Comment by saidghamra** [comment]
- [ ] I am not taken back to the deployments page when I successfully edit a deployment

**Comment by MarcDAFrame** [comment]
"The confirm password input field is not validated " it's because I used @agoracloud/common ChangePasswordDTO instead of the custom one i was using earlier.

ChangePasswordDTO doesn't have the same check for if `password === confirmPassword`

**Comment by saidghamra** [comment]
> "The confirm password input field is not validated " it's because I used @agoracloud/common ChangePasswordDTO instead of the custom one i was using earlier.
> 
> ChangePasswordDTO doesn't have the same check for if `password === confirmPassword`

The `ChangePasswordDto` class doesn't have the second password property because the server doesn't need it, which now explains why the confirm password input field isn't being validated if that same dto class was being used in the ui 👀

**Comment by saidghamra** [comment]
- [ ]  There is no error message indicating why the second confirm password input field is incorrect:

![image](https://user-images.githubusercontent.com/35788699/143150451-095ca974-2744-4099-b120-fc86bfdb2e20.png)

**Comment by saidghamra** [comment]
The UI is now bug free 🎉🎉🎉
